version: '2'

# la xarxa 1 farà servir les adreces 10.20.1.0/16
# la xarxa 2 farà servir les adreces 20.30.1.0/16
# la xarxa 3 farà servir les adreces 30.40.1.0/16
 

services:
  
  dhcpclientx2:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx2
    container_name: dhcpclientx2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x2:
        ipv4_address: 20.30.1.101

  dhcpclientx3:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx3
    container_name: dhcpclientx3
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x3:
        ipv4_address: 10.20.1.101

  dhcpclientx1:
    image: joaniznardo/ubuntum7base
    privileged: true
    mem_limit: 100m
    hostname: dhcpclientx1
    container_name: dhcpclientx1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      x1:
        ipv4_address: 30.40.1.101

  dhcpserver:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcpserver
    container_name: dhcpserver
    networks:
      x1:
        ipv4_address: 30.40.1.100
  
  dhcprelayx2:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcprelayx2
    container_name: dhcprelayx2
    networks:
      x1:
        ipv4_address: 30.40.1.99 
      x2:
        ipv4_address: 20.30.1.100
  
  dhcprelayx3:
    image: joaniznardo/ubuntum7dhcp1
    privileged: true
    mem_limit: 100m
    hostname: dhcprelayx3
    container_name: dhcprelayx3
    networks:
      x1:
        ipv4_address: 30.40.1.98 
      x3:
        ipv4_address: 10.20.1.100
  
networks:
  x1:
    ipam:
      driver: default
      config:
        - subnet: 30.40.0.0/16
          ip_range: 30.40.1.0/30
          gateway: 30.40.1.1
          aux_addresses:
            host1: 30.40.1.2
            host2: 30.40.1.3
            host0: 30.40.1.0

  x2:
    ipam:
      driver: default
      config:
        - subnet: 20.30.0.0/16
          ip_range: 20.30.1.0/30
          gateway: 20.30.1.1
          aux_addresses:
            host1: 20.30.1.2
            host2: 20.30.1.3
            host0: 20.30.1.0
  x3:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
          ip_range: 10.20.1.0/30
          gateway: 10.20.1.1
          aux_addresses:
            host1: 10.20.1.2
            host2: 10.20.1.3
            #~ host0: 10.20.1.0
